/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.gerenciadorTarefas;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo
 */
public class FrTarefas extends javax.swing.JFrame {

    /**
     * Creates new form FrTarefas
     */
    public FrTarefas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtListaGeral = new javax.swing.JTextArea();
        btnRemover = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnListarVazios = new javax.swing.JButton();
        btnContador = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        btnExcluirTodas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnMoverTopo = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel.setBackground(new java.awt.Color(153, 153, 153));
        JPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Insira a Tarefa:");
        JPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 144, -1, -1));

        edtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtNomeKeyPressed(evt);
            }
        });
        JPanel.add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 610, 50));

        btnAdicionar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdicionar.setText("Adicionar Tarefa");
        btnAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        JPanel.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 250, 50));

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Tarefas Criadas:");
        JPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        txtListaGeral.setColumns(20);
        txtListaGeral.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtListaGeral.setRows(5);
        jScrollPane1.setViewportView(txtListaGeral);

        JPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 610, 470));

        btnRemover.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRemover.setText("Remover Tarefa");
        btnRemover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        JPanel.add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 240, 50));

        btnVisualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVisualizar.setText("Listar Tarefas");
        btnVisualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        JPanel.add(btnVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 240, 50));

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditar.setText("Editar Tarefa");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        JPanel.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 240, 50));

        btnListarVazios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnListarVazios.setText("Checar Lista Vazia");
        btnListarVazios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListarVazios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarVaziosActionPerformed(evt);
            }
        });
        JPanel.add(btnListarVazios, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, 240, 50));

        btnContador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnContador.setText("Quantidade de Tarefas");
        btnContador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContadorActionPerformed(evt);
            }
        });
        JPanel.add(btnContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 600, 240, 50));

        btnOrdenar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOrdenar.setText("Ordenar Tarefas");
        btnOrdenar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        JPanel.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 240, 50));

        btnExcluirTodas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnExcluirTodas.setText("Excluir Todas Tarefas");
        btnExcluirTodas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirTodas.setMargin(new java.awt.Insets(2, 14, 2, 15));
        btnExcluirTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTodasActionPerformed(evt);
            }
        });
        JPanel.add(btnExcluirTodas, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 660, 240, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Imagem1-removebg-preview.png"))); // NOI18N
        JPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 190, 150));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Imagem2.png"))); // NOI18N
        JPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 100, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Imagem2.png"))); // NOI18N
        JPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 100, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Imagem2.png"))); // NOI18N
        JPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 100, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Imagem2.png"))); // NOI18N
        JPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 110, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Imagem2.png"))); // NOI18N
        JPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, 100, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Imagem2.png"))); // NOI18N
        JPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 100, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Imagem2.png"))); // NOI18N
        JPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 600, 100, 50));

        btnMoverTopo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMoverTopo.setText("Mover Tarefa");
        btnMoverTopo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoverTopoActionPerformed(evt);
            }
        });
        JPanel.add(btnMoverTopo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 720, 240, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Imagem2.png"))); // NOI18N
        JPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, 100, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Imagem2.png"))); // NOI18N
        JPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 720, 100, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        Gerenciador obj = new Gerenciador();
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        obj.adicionar(edtNome.getText());
        edtNome.setText("");
        edtNome.requestFocus();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        btnVisualizar.doClick();
        int cod;
        String novaTarefa;
        cod = Integer.parseInt(JOptionPane.showInputDialog("QUAL TAREFA SERÁ ALTERADA? "));
        novaTarefa = JOptionPane.showInputDialog("QUAL TAREFA SERÁ INSERIDA? ");
        obj.editar((cod-1), novaTarefa);
        txtListaGeral.setText(obj.visualizar());
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        txtListaGeral.setText(obj.visualizar());
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void btnListarVaziosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarVaziosActionPerformed
        txtListaGeral.setText(obj.visualizarVazia());
    }//GEN-LAST:event_btnListarVaziosActionPerformed

    private void edtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtNomeKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           btnAdicionar.doClick();
       }
    }//GEN-LAST:event_edtNomeKeyPressed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        btnVisualizar.doClick();
        int cod;
        cod= Integer.parseInt(JOptionPane.showInputDialog("QUAL O CÓDIGO DA TAREFA?"));
        if(JOptionPane.showConfirmDialog(null, "TEM CERTEZA QUE DESEJA REMOVER ESSA TAREFA? ","CONFIRME",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        obj.remover(cod-1);
        txtListaGeral.setText(obj.visualizar());
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnExcluirTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTodasActionPerformed
        if(JOptionPane.showConfirmDialog(null, "TEM CERTEZA QUE DESEJA EXCLUIR TODAS AS TAREFAS? ","CONFIRME",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
            obj.excluir();
        JOptionPane.showMessageDialog(null, "TAREFAS EXCLUIDAS COM SUCESSO");
        txtListaGeral.setText(obj.visualizar());
    }//GEN-LAST:event_btnExcluirTodasActionPerformed

    private void btnContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContadorActionPerformed
        obj.verificarQuant();
        txtListaGeral.setText(obj.visualizar());
    }//GEN-LAST:event_btnContadorActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        obj.ordernar();
        txtListaGeral.setText(obj.visualizar());
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnMoverTopoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoverTopoActionPerformed
       btnVisualizar.doClick();
       obj.moverTopo();
       btnVisualizar.doClick();
    }//GEN-LAST:event_btnMoverTopoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrTarefas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnContador;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluirTodas;
    private javax.swing.JButton btnListarVazios;
    private javax.swing.JButton btnMoverTopo;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JTextField edtNome;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtListaGeral;
    // End of variables declaration//GEN-END:variables
}
